# Configuraci칩n de Spring Kafka
spring:
  kafka:
    bootstrap-servers: localhost:9092  # Direcci칩n del servidor Kafka
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Puerto donde correr치 tu aplicaci칩n
server:
  port: 8080
